version: "3.3"
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=vm2
      - INFLUXDB_ADMIN_PASSWORD=FEFEfefe@1 
volumes:
  influxdb-storage:  
networks: 
  default: 
    external: 
      name: home-lab 