version: "3.3"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning 
    environment:
      - GF_SECURITY_ADMIN_USER=vm2
      - GF_SECURITY_ADMIN_PASSWORD=FEFEfefe@1
      - GF_RENDERING_SERVER_URL=http://192.168.18.127:8081/render
      - GF_RENDERING_CALLBACK_URL=http://192.168.18.127:3000/
      - GF_LOG_FILTERS=rendering:debug 
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1ms 
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - '8081:8081' 
volumes: 
  grafana-storage: 
networks: 
  default: 
    external: 
      name: home-lab 