version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo 
    network_mode: host
    volumes:
      - node-red-data:/data

volumes:
  node-red-data: 
networks: 
  default: 
    external: 
      name: home-lab 