version: '3'
services:
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://192.168.18.127:8086
      - INFLUXDB_USERNAME=vm2
      - INFLUXDB_PASSWORD=FEFEfefe@1 
volumes:
  chronograf-storage: 
networks: 
  default: 
    external: 
      name: home-lab 